name: Generate File List

on:
  push:
    branches:
      - main  # или ваша основная ветка

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate file list
        run: |
          find . -type f -not -path "./.git/*" -print0 | sort -z | xargs -0 printf "%s\n" > file_list.txt

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Update file list"
          file_pattern: file_list.txt
